title: "IRENE-AE9/AP9/SPM"
description: "Radiation Belt and Space Plasma Specification Models — Air Force Research Laboratory (AFRL)"
baseurl: "/ae9ap9"
url: "https://yourusername.github.io"

theme: null

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

navigation:
  - title: Home
    url: /
  - title: News
    url: /pages/news
  - title: Factsheet
    url: /pages/factsheet
  - title: Quick Reference
    url: /pages/quick-reference/
  - title: Documents
    url: /pages/documents
  - title: Validations
    url: /pages/validations
  - title: Downloads
    url: /pages/downloads
  - title: Team
    url: /pages/team
  - title: DSX
    url: /pages/dsx
